### PR TITLE
ObjectGuid: Part I.

### PR DESCRIPTION
**Pull request by UltraNix**

### CODE REVIEW

**Comment by UltraNix** [comment]
Failed at DB import - unrelated to the PR.

**Comment by UltraNix** [comment]
Ready to be merged.

**Comment by FrancescoBorzi** [comment]
@UltraNix build fails

**Comment by UltraNix** [comment]
@FrancescoBorzi Not my fault - I haven't changed any SQL file.

**Comment by locus313** [comment]
@UltraNix fix the sql here as well, can you update the pr?

**Comment by UltraNix** [comment]
@locus313 Done.

**Pull request merged**
